### ISSUE TITLE
How to install dcem in google colab?

### ISSUE THREAD

**Issue by xgxgnpu** [facebookresearch/dcem#1]
Thanks for your nice repositor! I have no idea how to install dcem in google colab. I am trying to solve the problem by looking for some answers on Internet but failed. My problem is as follows
I use this code to install dcem in google colab
`
!pip install git+git://github.com/facebookresearch/dcem.git
`

but the error occurs
`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+git://github.com/facebookresearch/dcem.git
  Cloning git://github.com/facebookresearch/dcem.git to /tmp/pip-req-build-a_rm3sd7
  Running command git clone -q git://github.com/facebookresearch/dcem.git /tmp/pip-req-build-a_rm3sd7
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.3]: errno=Connection timed out

WARNING: Discarding git+git://github.com/facebookresearch/dcem.git. Command errored out with exit status 128: git clone -q git://github.com/facebookresearch/dcem.git /tmp/pip-req-build-a_rm3sd7 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/facebookresearch/dcem.git /tmp/pip-req-build-a_rm3sd7 Check the logs for full command output.`

I don't know how to deal with it, could you please give me some advice? Thank you in advance!

**Comment by bamos** [comment]
I don't use colab and I'm not too, sure but it looks like there is some problem connecting to github to clone the repo from these lines

```
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
```

Can you try manually cloning the repo and running `python3 setup.py develop` to set it up?

**Comment by xgxgnpu** [comment]
> I don't use colab and I'm not too, sure but it looks like there is some problem connecting to github to clone the repo from these lines
> 
> ```
> fatal: unable to connect to github.com:
> github.com[0: 140.82.121.3]: errno=Connection timed out
> ```
> 
> Can you try manually cloning the repo and running `python3 setup.py develop` to set it up?

Yes, i try it in another way and it works. I  cloned the repo manually in colab and install dependency with the following code
`!pip install git+https://github.com/denisyarats/dmc2gym`
`!pip install git+https://github.com/locuslab/lml`

then i can use your dcem in my colab, thanks a lot for your nice reply and repository again!

**Comment by bamos** [comment]
great!
